### ISSUE TITLE
Auto zoom out

### ISSUE THREAD

**Issue by furiosFast** [tungfam/ImageInNavigationBarDemo#6]
Hi, 
there is a issue when you open a detail segue and the image is in small state

**Comment by tungfam** [comment]
Hi @furiosFast ! Thanks for opening an issue.

May I clarify, which are the steps to reproduce?
Since I just cloned the project and checked: when I open the detail screen there is no image (nor big or small).

Is it how it works on your side too?
![2018-07-14 12 20 02](https://user-images.githubusercontent.com/17186720/42723102-4816e53a-8760-11e8-9a86-063c57120c11.gif)

If no, please let me know, we can check what's the issue.

**Comment by furiosFast** [comment]
i've update che code inside my app and this is the result: hide

**Comment by furiosFast** [comment]
and this is the effect error: hide

**Comment by tungfam** [comment]
@furiosFast thanks for the videos, it makes it more clear what is the problem.

First of all, you need to understand that this project (ImageInNavigationBarDemo) is not a Pod or a library. It is the tutorial code. And as long as you implement it right on your side it will work correctly, otherwise not.

As you can see, if you install the demo project you won't see this issue, which means most likely that your implementation might be not the same, which is totally correct since you have your own logic in your app and so on.

But I can help you to understand the issue. As I see you are not re-assigning the image of ImageView but you are adding the new one. That's why it:
1. Doesn't resize because it doesn't know which image to resize most likely
2. Has 2 images in the top corner instead of 1

Solution: have 1 instance of ImageView and re-assign the UIImage in it.

2nd video - not sure if I understood the issue. Could you please elaborate?

Hope it helps.

**Comment by furiosFast** [comment]
Thanks anyway, but I managed to solve in another way
